name: ausgrid_application
description: "A new Flutter project."
publish_to: 'none' # This keeps it private and off pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  speech_to_text: ^6.3.0
  geolocator: ^10.0.1
  http: ^0.13.5
  flutter_tts: ^4.2.3
  file_picker: ^6.1.1
  permission_handler: ^11.0.0
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png

